import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/Link'
import { Inter } from '@next/font/google'
import {BiUserPlus} from 'react-icons/bi'
import { Form, Table } from '../components'
import { useState } from 'react'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [visible,setVisible] = useState(false)
  return (
		<section className="flex justify-center">
			<Head>
				<title>NEXT JS CRUD APP</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-5">
				<h1 className="text-3xl text-center font-bold">
					Employee Management Application
				</h1>

				<div className="container mx-auto flex justify-between py-5 border-b">
					<div className=" left flex gap-3">
						<button onClick={() => setVisible(!visible)} className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-500">
							Add Employee{" "}
							<span className="px-1">
								<BiUserPlus size={25} />
							</span>
						</button>
					</div>

					{/* collapsable form */}
          <div className="container mx-auto py-5">
            {visible ? <Form/> : '' }
          </div>
				</div>
				<div className="container mx-auto">
					<Table />
				</div>
			</main>
		</section>
	);
}
