import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Google Drive Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello people</h1>
      </div>
    </>
  );
}

export default Home