import Dashboard from "@/components/Dashboard";
import Header from "@/components/Header";
import SideBar from "@/components/Sidebar";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Google Drive Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="main-container" >
        <SideBar />
        <Dashboard />
      </div>
    </>
  );
}

export default Home