
import React from 'react'
import Head from 'next/head'
import Script from 'next/Script'
import Image from 'next/image'
import flat1 from '../../public/images/flat (1).jpg'
import styles from '../../styles/sass/style.module.scss'

const Post = () => {
  return (
		<div>
			<Head>
				<title>Create a first post</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
        <Script  src="" strategy='lazyOnload' onLoad={{}}></Script>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title} >first post</h1>
      <Image  
        src={flat1}
        // layout="fill"
        width={500}
        height={500}
      />
      {/* <Image 
        src="../../public/images/flat (2).jpg"
        width={300}
        height={300}
      /> */}

		</div>
	);
}

export default Post