import Head from 'next/head'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
		<section className="flex justify-center">
			<Head>
				<title>NEXT JS CRUD APP</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-12">
        <div className="m-auto">
					<h2 className='text-3xl text-orange-900 text-center' >Hello my world</h2>
				</div>
			</main>
		</section>
	);

}