
import React from 'react'
import Head from 'next/head'
import Script from 'next/Script'

const Post = () => {
  return (
		<div>
			<Head>
				<title>Create a first post</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
        <Script  src="" strategy='lazyOnload' onLoad={{}}></Script>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>first post</h1>
		</div>
	);
}

export default Post