import Head from 'next/head'
import Link from 'next/link'
import React, { useContext,useState,useEffect } from "react";
import { Store } from "../utils/Store";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import {useSession} from 'next-auth/react'
import { Menu } from '@headlessui/react';
import {DropdownLink} from '../components'
import Cookies from 'js-cookie'
import {signOut} from 'next-auth/react'

const Layout = ({children,title}) => {
	const {status,data:session} = useSession()
	const { state, dispatch } = useContext(Store);
  const {cart} = state
  const [cartItemsCount,setCartItemsCount] = useState(0)

  useEffect(()=>{
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  },[cart.cartItems])

	const logoutClickHandler = () => {
		Cookies.remove("cart");
		dispatch({ type: "CART_RESET" });
		signOut({ callbackUrl: "/login" });
	};
  return (
		<>
			<Head>
				<title>{title ? title + " Amazona" : "Amazon"}</title>
				<meta name="description" content="Generated by next app" />
				<link
					rel="shortcut icon"
					href="/public/favicon.ico"
					type="image/x-icon"
				/>
			</Head>
			<ToastContainer position="bottom-center" limit={1} />
			<div className="flex min-h-screen flex-col justify-between">
				<header>
					<nav className="flex h-12 justify-between shadow-md items-center px-4">
						<Link className="text-lg font-bold" href="/">
							amazona
						</Link>
						<div>
							<Link className="p-2" href="/cart">
								Cart
								{cart.cartItems.length > 0 && (
									<span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
										{cartItemsCount}
									</span>
								)}
							</Link>
							{status === "loading" ? (
								"Loading"
							) : session?.user ? (
								<Menu as="div" className="relative inline-block">
									<Menu.Button className="text-blue-600">
										{session.user.name}
									</Menu.Button>
									<Menu.Items className="absolute right-0 w-56 origin-top-right bg-white  shadow-lg ">
										<Menu.Item>
											<DropdownLink className="dropdown-link" href="/profile">
												Profile
											</DropdownLink>
										</Menu.Item>
										<Menu.Item>
											<DropdownLink
												className="dropdown-link"
												href="/order-history"
											>
												Order History
											</DropdownLink>
										</Menu.Item>
										{session.user.isAdmin && (
											<Menu.Item>
												<DropdownLink
													className="dropdown-link"
													href="/admin/dashboard"
												>
													Admin Dashboard
												</DropdownLink>
											</Menu.Item>
										)}
										<Menu.Item>
											<span
												className="dropdown-link"
												// href="#"
												onClick={logoutClickHandler}
											>
												Logout
											</span>
										</Menu.Item>
									</Menu.Items>
								</Menu>
							) : (
								<Link href="/login" className="p-2">
									Login
								</Link>
							)}
						</div>
					</nav>
				</header>
				<main className="container m-auto mt-4 px-4">{children}</main>
				<footer className="flex justify-center items-center h-10 shadow-inner">
					<p>Copyright @ 2023 Charles</p>
				</footer>
			</div>
		</>
	);
}

export default Layout