import Head from 'next/head'
import Link from 'next/link'
import React, { useContext,useState,useEffect } from "react";
import { Store } from "../utils/Store";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import Loading from './Loading';

const Layout = ({children,title}) => {
	const { state } = useContext(Store);
  const {cart} = state
  const [cartItemsCount,setCartItemsCount] = useState(0)

  useEffect(()=>{
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  },[cart.cartItems])

	
  return (
		<>
			<Head>
				<title>{title ? title + " Amazona" : "Amazon"}</title>
				<meta name="description" content="Generated by next app" />
				<link
					rel="shortcut icon"
					href="/public/favicon.ico"
					type="image/x-icon"
				/>
			</Head>
			<ToastContainer position="bottom-center" limit={1} />
			<div className="flex min-h-screen flex-col justify-between">
				<header>
					<nav className="flex h-12 justify-between shadow-md items-center px-4">
						<Link
							suppressHydrationWarning={true}
							className="text-lg font-bold"
							href="/"
						>
							amazona
						</Link>
						<div>
							<Link
								className="p-2"
								href="/cart"
								suppressHydrationWarning={true}
							>
								Cart
								{cart.cartItems.length > 0 ? (
									<span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
										{cartItemsCount}
									</span>
								) : null}
							</Link>
							<Loading />
						</div>
					</nav>
				</header>
				<main className="container m-auto mt-4 px-4">{children}</main>
				<footer className="flex justify-center items-center h-10 shadow-inner">
					<p>Copyright @ 2023 Charles</p>
				</footer>
			</div>
		</>
	);
}

export default Layout