import Head from 'next/head'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {



	
  return (
		<section className="flex justify-center">
			<Head>
				<title>NEXT JS CRUD APP</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
			</Head>
      <div className="flex justify-center my-auto bg-red-400">
				<h1 className="text-3xl text-orange-600">
					Hello my app
				</h1>
			</div>
		</section>
	);
}
