import Head from 'next/head'



export default function Home() {


	const handler = () => {
	}
  return (
		<section className="flex justify-center">
			<Head>
				<title>NEXT JS CRUD APP</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-5">
				<h1 className="text-4xl text-orange-600 text-center">
					Hello My Instagram Clone 
				</h1>
			</main>
		</section>
	);
}
